apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: node-etcd-app
spec:
  replicas: 3
  template:
    metadata:
      name: node-etcd-app
      labels:
        run: clouddb-demo
    spec:
      containers:
      - name: node-etcd-app
        image: "<region>.icr.io/<namespace>/icdetcd" # Edit me
        imagePullPolicy: Always
        env:
        - name: BINDING
          valueFrom:
            secretKeyRef:
              name: <etcd-secret-name> # Edit me
              key: binding
---
apiVersion: v1
kind: Service
metadata:
  name: node-etcd-service
  labels:
    run: clouddb-demo
spec:
  type: NodePort
  selector:
    run: clouddb-demo
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30081